#! /bin/bash
if(($# == 1))
then
    FILE=$1
    if [[ -r ${FILE} ]]
    then
	flag1=1
	flag2=1
	itera=0
#	echo starts here
	while IFS= read line
	do
	    itera=$((${itera}+1));
	    flag1=1
	    flag2=1
#	    echo ${line}
	    element1=$(printf "${line}" | cut -d';' -f1-1)
	    element2=$(printf "${line}" | cut -d';' -f2-2)
	    namepattern1="[A-Z][a-z][a-z]*, [A-Z][a-z][a-z]* [A-Z].$"
	    namepattern2="[A-Z][a-z][a-z]*, [A-Z][a-z][a-z]*$"
	    if [[ ${element1} =~ ${namepattern1} || ${element1} =~ ${namepattern2} ]]
	    then
		flag1=1
	#	echo case1
	    else
		flag1=0
	#	echo case2
	    fi

	    element2=x${element2}x
#	    echo ${element2}
	    addnum=$(echo $element2 | wc -w)
#	    echo ${addnum}
	    addpattern1="[a-z][[:digit:]]*$"
	    addpattern2="[A-Z0-9][a-zA-Z0-9.]*$"
	    addpattern3="[A-Z0-9][a-zA-Z0-9.]*.$"
	    addpatternfi1="[A-Z0-9][a-zA-Z0-9.]*x$"
	    addpatternfi2="[A-Z0-9][a-zA-Z0-9.]*.x$"
	    addpatternx="x$"
	    for((I = 1; I <= ${addnum}; I++))
	    do
		nowword=$(echo ${element2} | cut -d' ' -f${I})
		if [[ ${addnum} < 1 ]]
		then
		    flag2=0
		elif [[ ${I} == 1 ]]
		then
		    if ! [[ ${nowword} =~ ${addpattern1} ]]
		    then
			flag2=0
	#		echo first is right $nowword
#			echo first is wrong $nowword
		    fi
		    if [[ ${nowword} =~ ${addpatternx} ]]
		    then
			flag2=0
	#		echo first is wrong
	#	    else
	#		echo first is right
		    fi
		    
		elif [[ ${I} == ${addnum} ]]
		then
		    if ! [[ ${nowword} =~ ${addpatternfi1} || ${nowword} =~ ${addpatternfi2} ]]
		    then
	        	flag2=0
	#		echo last is right $nowword
		
		
	#		echo last is wrong $nowword
		    fi
		else
		    if ! [[ ${nowword} =~ ${addpattern2} || ${nowword} =~ ${addpattern3} ]]
		    then
	        	flag2=0
	#		echo mid is right $nowword
		
	#		echo mid is wrong $nowword
		    fi
		fi
		
	    done
	    #    echo ${flag1} " " ${flag2}
	    if [[ ${flag1} == 0 && ${flag2} == 0 ]]
	    then
		echo "Line" ${itera} "has an invalid name and address!"
	    elif [[ ${flag1} == 1 && ${flag2} == 0 ]]
	    then
		echo "Line" ${itera} "has an invalid address!"
	    elif [[ ${flag1} == 0 && ${flag2} == 1 ]]
	    then
		echo "Line" ${itera} "has an invalid name!"
	    else
		echo "Line" ${itera} "is valid."
	    fi
	done < ${FILE}
	exit 0
    else
	echo "Error:" $FILE "is not readible!"
	exit 2
    fi
else
    echo "Usage: verify <filename>"
    exit 1
fi
